baseURL: https://icloudgo.net/
languageCode: en-us
title: iCloudGo
paginate: 5
theme: "PaperMod"

enableRobotsTXT: true

params:
  env: production
  defaultTheme: auto
  ShowReadingTime: true
  ShowToc: true
  #TocOpen: true
  assets:
    disableFingerprinting: true
  hideFooter: true
  keywords: [blog, tutorials, guides, IT, cloud]
  catagories: 
    - network security

menu:
  main:
    - identifier: search
      name: search
      url: /search/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary