baseURL: https://icloudgo.devok.store/
languageCode: en-us
title: KB (forked)
paginate: 5
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

menu:
  main:
    - identifier: search
      name: search
      url: /search/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
  env: production
  description: "iCloudGo.KB.Devok"
  author: George A.
  keywords: [blog, tutorials, guides, IT, cloud]
  categories: 
    - network security  
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: false
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  #TocOpen: true
  # comments: false
  
  homeInfoParams:
      Title: "Welcome to iCloudGo!"
      Content: >
        I started this blog as an excuse to try out Cloudflare Pages and a 
        place to capture my notes and thoughts on recent projects, configurations, and tools.
        Hopefully my tutorials and guides can also assist with your own projects. 
        Again, welcome and please reach out with any suggestions or questions. 
  
  socialIcons:
        - name: github
          url: "https://github.com/ggatesdew"
        #- name: KoFi
        #  url: "https://ko-fi.com/adityatelange"
        #- name: Rss
          url: "index.xml"

  assets:
    disableFingerprinting: true
    disableHLJS: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: false
    location: 0
    distance: 0
    threshold: 0.2
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content"]

markup:
  highlight:
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    noClasses: false
    # style: monokai

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: true
    simple: true
  twitter:
    disable: true
    enableDNT: true
    simple: true
  vimeo:
    disable: true
    enableDNT: true
    simple: true
  youtube:
    disable: true
    privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
